### PR TITLE
Add support for About methods

### PR DESCRIPTION
**Pull request by LoveMHz**
This adds support for the [About get method](https://developers.google.com/drive/v2/reference/about).

### CODE REVIEW

**Comment by niftylettuce** [comment]
see v0.0.8 in NPM

**Comment by niftylettuce** [comment]
if you'd like to maintain this project @LoveMHz please let me know - I also need to know your NPM username

**Comment by LoveMHz** [comment]
@niftylettuce Sure, this is the only library that currently supports my current project and will definitely be adding to it more. My NPM username is the as same here, lovemhz.

**Comment by niftylettuce** [comment]
Gave you GitHub collaborator + NPM owner access, happy hacking @LoveMHz - feel free to email me niftylettuce@gmail.com if you'd like to share what you're using it for!

**Comment by niftylettuce** [comment]
Also the Readme probably needs updated, there's also an open PR for something too if you wanted to help cleanup.  Issues probably needs maintained too.  Appreciate everything.

**Pull request merged**
